### PR TITLE
Fix docker startup script

### PR DESCRIPTION
**Pull request by eckdanny-osi**
yarn start and bash were complaining about foreman not being found.
(Guessing it was the && operator in the docker CMD). Moved the foreman
install into the Dockerfile and updated the docker CMD in startup
scripts.

I wasn't able to troubleshoot from my machine. (I'm out of disk space!)
Paired with @karthik-sista and @melbourne.

### CODE REVIEW

**Comment by edgibbs** [comment]
Can one of the admins verify this patch?

**Comment by eckdanny-osi** [comment]
Paired with @karthik-sista and @mlipardo

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
Build triggered. sha1 is merged.

**Comment by edgibbs** [comment]
Build started sha1 is merged.

**Comment by edgibbs** [comment]
Not sure why the build doesn't always seem to be triggered by the pull request.

**Comment by edgibbs** [comment]
Everything is green!

**Pull request merged**
