### PR TITLE
Update js deps

### PR DESCRIPTION
**Pull request by eckdanny-osi**
just some js dep maintenance

### CODE REVIEW

**Comment by edgibbs** [comment]
Can one of the admins verify this patch?

**Comment by eckdanny-osi** [comment]
```
$ yarn outdated
yarn outdated v1.2.1
✨  Done in 1.37s.
````

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Pull request merged**
