### PR TITLE
Update web packer gem to 3.2

### PR DESCRIPTION
**Pull request by edgibbs**
Saw a strange issue where locally webpacker wasn't resolving the link to dashboard stylesheet.  Upgrading the gem fixed the issue.

### CODE REVIEW

**Comment by SashaKyz** [comment]
Can one of the admins verify this patch?

**Comment by eckdanny-osi** [comment]
Awesome. I was just considering opening this issue. Ran into some funniness with an npm dep that got replaced in 3.2.0 ([release notes](https://github.com/rails/webpacker/blob/master/CHANGELOG.md#added-npm-module))

**Comment by edgibbs** [comment]
Good catch, usually gems don't require anything other than an update to the gemfile, so I didn't think about the related javascript packages.

**Comment by eckdanny-osi** [comment]
added the postcss bits from upgrade guide

**Pull request merged**
