### PR TITLE
Add link list

### PR DESCRIPTION
**Pull request by eckdanny-osi**
Closes https://osi-cwds.atlassian.net/browse/CASE-64

Style hacks in place until wood-duck ships a component.

### CODE REVIEW

**Comment by edgibbs** [comment]
I'm just not sure application.css is the best place for these hacks.

**Comment by eckdanny-osi** [comment]
The CM team discussed the path to "hoisting" components (one-offs -> app-like-module -> _components -> wood-duck). Will open an issue (label: docs) to capture decisions regarding the practice.

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
Added @RamuKammagani-osi as reviewer

**Pull request merged**
