### PR TITLE
Add git.legal to Code Climate

### PR DESCRIPTION
**Pull request by eckdanny-osi**
See https://osi-cwds.atlassian.net/browse/CASE-37

### CODE REVIEW

**Comment by edgibbs** [comment]
Can one of the admins verify this patch?

**Comment by eckdanny-osi** [comment]
Raises an error on CC:

```
codeclimate validate-config
ERROR: only use one of 'engines', 'plugins'
WARNING: missing 'version' key. Please add `version: "2"`
WARNING: 'engines' has been deprecated, please use 'plugins' instead
WARNING: 'exclude_paths' has been deprecated, please use 'exclude_patterns' instead
WARNING: 'ratings' has been deprecated, and will not be used
```

https://codeclimate.com/repos/5991e8661a3e44026400036c/pull/75

**Comment by edgibbs** [comment]
Build triggered. sha1 is merged.

**Comment by edgibbs** [comment]
Build started sha1 is merged.

**Comment by edgibbs** [comment]
Everything is green!

**Comment by edgibbs** [comment]
Build triggered. sha1 is merged.

**Comment by edgibbs** [comment]
Build started sha1 is merged.

**Comment by edgibbs** [comment]
Everything is green!

**Comment by edgibbs** [comment]
Build triggered. sha1 is merged.

**Comment by edgibbs** [comment]
Build started sha1 is merged.

**Comment by edgibbs** [comment]
Everything is green!

**Comment by edgibbs** [comment]
OK, I believe this is passing in code climate, not sure why that isn't reflected in the status check, but even if it is still failing we will have to mitigate anyway.

**Pull request merged**
