### PR TITLE
Sortable data tables

### PR DESCRIPTION
**Pull request by eckdanny-osi**
sortable

### CODE REVIEW

**Comment by edgibbs** [comment]
test this please

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest test please

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by SashaKyz** [comment]
hello

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
please retest this

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
Can one of the admins verify this patch?

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by SashaKyz** [comment]
Can one of the admins verify this patch?

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Pull request merged**
