### PR TITLE
Config is dead long live config

### PR DESCRIPTION
**Pull request by eckdanny-osi**
addresses the remaining pains in #176

* [x] unit tests _independent_ of ENV vars
* [x] removes all grouped yml configs for better 12f (ALL feature flags and backing services are set via ENV vars)

### CODE REVIEW

**Comment by SashaKyz** [comment]
Can one of the admins verify this patch?

**Comment by eckdanny-osi** [comment]
_Oh!_ Jenkins will complain until #213 is merged since I reverted that delta in a6fa956 for a standalone PR.

**Comment by eckdanny-osi** [comment]
👀 The `ServiceRegistry` module is _not actually used_. The module really only does 2 things: 

 - provides a bit of insulation around ENV
 - translates `:symbol` to `'SYMBOL'` for `ENV#fetch` lookups

I'd personally rather deal with ENV directly, but i'm including the implementation to promote PR feedback.

**Comment by eckdanny-osi** [comment]
Also, since all `ENV` APIs are mocked, there is no need for CI to pull from private repo or be manually maintained

**Comment by eckdanny-osi** [comment]
@edgibbs feedback?

**Comment by edgibbs** [comment]
retest this please

**Pull request closed without merging**
