### PR TITLE
Implement eslint checks for unsanitized html

### PR DESCRIPTION
**Pull request by edgibbs**
Implements an 18F recommended security check.  The dependencies in yarn.lock look fine, but I did notice it migrated some packages down like babel versions, so the second pair of eyes on it is good.

### CODE REVIEW

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by eckdanny-osi** [comment]
we may consider blacklisting [`dangerouslysetinnerhtml()`](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml). Perhaps later.

**Comment by edgibbs** [comment]
That is a classic xkcd strip.

**Pull request merged**
