### PR TITLE
Add run script to build CSV of licnses in use

### PR DESCRIPTION
**Pull request by eckdanny-osi**
usage:

```
$ yarn license-dump > list.csv
$ case-management tail list.csv

"yargs-parser@4.2.1","ISC","https://github.com/yargs/yargs-parser"
"yargs-parser@5.0.0","ISC","https://github.com/yargs/yargs-parser"
"yargs-parser@7.0.0","ISC","https://github.com/yargs/yargs-parser"
"yargs@3.10.0","MIT","https://github.com/bcoe/yargs"
"yargs@6.6.0","MIT","https://github.com/yargs/yargs"
"yargs@7.1.0","MIT","https://github.com/yargs/yargs"
"yargs@8.0.2","MIT","https://github.com/yargs/yargs"
"yargs@9.0.1","MIT","https://github.com/yargs/yargs"
```

### CODE REVIEW

**Comment by eckdanny-osi** [comment]
@brunoOSI @ratneshraval

**Comment by eckdanny-osi** [comment]
Is this _already_ a feature of `yarn`? https://github.com/yarnpkg/yarn/issues/904

The ask today in JAM was to generate CSV formatted list, but we may be able to do better if we recycle their classification scheme (good, conditionally good, bad) into an automated process

**Comment by edgibbs** [comment]
Can one of the admins verify this patch?

**Comment by eckdanny-osi** [comment]
The `yarn` feature in an accepted RFC. AFAIK, it has not been implemented in `yarn` yet. The current signature is `yarn licenses [ls|list|generate-disclaimer] [flags]` with no ability to specify output format (csv).

So the above is the best sol'n for now.

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please.

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
test this please

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Pull request merged**
