### PR TITLE
Created a link on the Landing Page to Navigate to Client ID Page

### PR DESCRIPTION
**Pull request by karthik-sista**

### CODE REVIEW

**Comment by edgibbs** [comment]
Build triggered. sha1 is merged.

**Comment by edgibbs** [comment]
Build started sha1 is merged.

**Comment by edgibbs** [comment]
Everything is green!

**Comment by edgibbs** [comment]
So we're just linking this?

**Comment by karthik-sista** [comment]
@edgibbs  As far as i understand, there should be just a Link on the landing page, but there are no styling/any info on where exactly the link sits on the page. So i just created a link underneath the cards.

**Comment by edgibbs** [comment]
Build triggered. sha1 is original commit.

**Comment by edgibbs** [comment]
Build started sha1 is original commit.

**Comment by edgibbs** [comment]
Failing is feedback.

**Comment by eckdanny-osi** [comment]
^ looks like a failing unit test. @karthik-sista can u resolve and push update to PR branch?

**Comment by eckdanny-osi** [comment]
paring with @karthik-sista 

There have been breaking changes introduced in wood duck (`0.1.35` -> `0.1.36) The `sideNav` component was removed? The component props for the new `sideBar` component are not compatible.

**Pull request merged**
