### PR TITLE
Landing Page, Page header and customer profile box.

### PR DESCRIPTION
**Pull request by mlipardo**
Added a landing page, page header and card component from react-wood-duck.

### CODE REVIEW

**Comment by edgibbs** [comment]
Can one of the admins verify this patch?

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
Build triggered. sha1 is merged.

**Comment by edgibbs** [comment]
Build started sha1 is merged.

**Comment by edgibbs** [comment]
Everything is green!

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
Build triggered. sha1 is merged.

**Comment by edgibbs** [comment]
Build started sha1 is merged.

**Comment by edgibbs** [comment]
Everything is green!

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
Build triggered. sha1 is original commit.

**Comment by edgibbs** [comment]
Build started sha1 is original commit.

**Comment by edgibbs** [comment]
Everything is green!

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
Build triggered. sha1 is original commit.

**Comment by edgibbs** [comment]
Build started sha1 is original commit.

**Comment by edgibbs** [comment]
Everything is green!

**Comment by RamuKammagani-osi** [comment]
Can you please update your react-wood-duck version?

**Comment by eckdanny-osi** [comment]
retest this please

**Comment by eckdanny-osi** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by edgibbs** [comment]
Build triggered. sha1 is merged.

**Comment by edgibbs** [comment]
Build started sha1 is merged.

**Comment by edgibbs** [comment]
Everything is green!

**Pull request merged**
