### PR TITLE
Added missing dependency in Package.json

### PR DESCRIPTION
**Pull request by RamuKammagani-osi**
Moment library added, Now we can see that in Package.json !

### CODE REVIEW

**Comment by SashaKyz** [comment]
Can one of the admins verify this patch?

**Comment by eckdanny-osi** [comment]
haha getting stuff done during planning ceremony ;)

**Comment by amanbop** [comment]
@eckdanny-osi @edgibbs Pls approve and merge

**Comment by RamuKammagani-osi** [comment]
closes #193 issue

**Comment by RamuKammagani-osi** [comment]
#193

**Comment by eckdanny-osi** [comment]
@RamuKammagani-osi just put the "Closes #193" in the PR description and issue will be closed automagically:

 > You can include keywords in your pull request titles and descriptions, as well as commit messages, to automatically close issues in GitHub.

**Comment by RamuKammagani-osi** [comment]
Sure! will do that from next time  @eckdanny-osi

**Pull request merged**
