### PR TITLE
👀 Remove the map feature XHR stubs

### PR DESCRIPTION
**Pull request by eckdanny-osi**
👀

### CODE REVIEW

**Comment by SashaKyz** [comment]
Can one of the admins verify this patch?

**Comment by eckdanny-osi** [comment]
Don't know if removing the stub works with _no_ tinkering yet... This may be a db2data issue. What `clientId` seems to work for our db snapshot?

**Comment by eckdanny-osi** [comment]
_Oh!_ When things didn't work automatically, I noticed the stack trace in rails std out:

```
Started GET "/api/placements/0YIPkZU0S0" for 127.0.0.1 at 2018-02-02 21:43:29 -0800
Processing by Api::PlacementsController#clients_by_related_client_id as JSON
  Parameters: {"client_id"=>"0YIPkZU0S0"}
Completed 500 Internal Server Error in 64ms

Faraday::ParsingError (765: unexpected token at '<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /child-clients/0YIPkZU0S0/addresses. Reason:
<pre>    Not Found</pre></p>
</body>
</html>
'):

...
```

Question: why does the JSON web service _ever_ respond with an HTML document? If any response body is present, i'd expect it to be a JSON repr of the error (e.g.; maybe a generic message, possibly a stack trace in development, or a debugging tracking id in production or something). What's up here?

**Comment by eckdanny-osi** [comment]
closing in favor of #217

**Pull request closed without merging**
